"""Sentinel replies used by Florence messaging protocol operator turns."""

from __future__ import annotations


ONBOARDING_SYNC_WAITING_SENTINEL = "HANDOFF_TO_SYNC_WAITING"
ONBOARDING_CONTEXTUAL_CHAT_SENTINEL = "HANDOFF_TO_CONTEXTUAL_CHAT"
ONBOARDING_NO_REPLY_SENTINEL = "NO_SETUP_REPLY"
REVIEW_SHOW_PROMPT_SENTINEL = "SHOW_CURRENT_REVIEW_PROMPT"
REVIEW_NO_ACTION_SENTINEL = "NO_REVIEW_PROTOCOL_ACTION"
GROUP_SHARE_EXECUTE_SENTINEL = "EXECUTE_GROUP_SHARE"
GROUP_SHARE_NO_ACTION_SENTINEL = "NO_GROUP_SHARE_PROTOCOL_ACTION"
GROUP_INTRO_SHOW_SENTINEL = "SHOW_GROUP_INTRO"
GROUP_INTRO_NO_ACTION_SENTINEL = "NO_GROUP_INTRO_PROTOCOL_ACTION"
HEARTBEAT_OK_SENTINEL = "HEARTBEAT_OK"

PROTOCOL_SENTINELS = frozenset(
    {
        ONBOARDING_SYNC_WAITING_SENTINEL,
        ONBOARDING_CONTEXTUAL_CHAT_SENTINEL,
        ONBOARDING_NO_REPLY_SENTINEL,
        REVIEW_SHOW_PROMPT_SENTINEL,
        REVIEW_NO_ACTION_SENTINEL,
        GROUP_SHARE_EXECUTE_SENTINEL,
        GROUP_SHARE_NO_ACTION_SENTINEL,
        GROUP_INTRO_SHOW_SENTINEL,
        GROUP_INTRO_NO_ACTION_SENTINEL,
    }
)


def looks_like_protocol_sentinel(reply_text: str | None) -> bool:
    """Return true when a model reply leaked an internal protocol sentinel."""
    return str(reply_text or "").strip() in PROTOCOL_SENTINELS
