"""Deterministic DM-first onboarding state and flows for Florence."""

from florence.onboarding.flow import (
    apply_household_members,
    apply_household_operations,
    apply_nudge_preferences,
    apply_operating_preferences,
    OnboardingPrompt,
    OnboardingTransition,
    apply_activity_basics,
    apply_child_names,
    apply_parent_name,
    apply_school_basics,
    build_google_connected_syncing_message_sequence,
    build_google_connect_message,
    build_google_connect_message_sequence,
    build_onboarding_ready_message_sequence,
    build_onboarding_prompt,
    build_sync_complete_finish_profile_message_sequence,
    build_web_onboarding_handoff_sequence,
    mark_google_connected,
    mark_group_activated,
    sync_onboarding_stage,
)
from florence.onboarding.links import (
    FlorenceOnboardingLinkState,
    decode_onboarding_link_state,
    encode_onboarding_link_state,
)
from florence.onboarding.parsing import extract_child_names, split_entries, split_labels, split_names
from florence.onboarding.state import OnboardingStage, OnboardingState, OnboardingVariant

__all__ = [
    "FlorenceOnboardingLinkState",
    "OnboardingPrompt",
    "OnboardingStage",
    "OnboardingState",
    "OnboardingVariant",
    "OnboardingTransition",
    "apply_activity_basics",
    "apply_child_names",
    "apply_household_members",
    "apply_household_operations",
    "apply_nudge_preferences",
    "apply_operating_preferences",
    "apply_parent_name",
    "apply_school_basics",
    "build_google_connected_syncing_message_sequence",
    "build_google_connect_message",
    "build_google_connect_message_sequence",
    "build_onboarding_ready_message_sequence",
    "build_onboarding_prompt",
    "build_sync_complete_finish_profile_message_sequence",
    "build_web_onboarding_handoff_sequence",
    "decode_onboarding_link_state",
    "encode_onboarding_link_state",
    "extract_child_names",
    "mark_google_connected",
    "mark_group_activated",
    "split_entries",
    "split_labels",
    "split_names",
    "sync_onboarding_stage",
]
