"""Shared relevance hints and helpers for Florence Google candidate scoring."""

from __future__ import annotations

LOGISTICS_HINTS = (
    "no class",
    "class canceled",
    "class cancelled",
    "canceled",
    "cancelled",
    "closed",
    "family day",
    "picture day",
    "picture retake",
    "photo retake",
    "recital",
    "field trip",
    "early dismissal",
    "dismissal",
    "late start",
    "no school",
    "open house",
    "conference",
    "concert",
    "performance",
    "practice",
    "orientation",
    "graduation",
    "ceremony",
    "spirit day",
    "holiday",
    "break",
    "schedule",
    "calendar",
    "pickup",
    "pick up",
    "pickup window",
    "drop off",
    "dropoff",
    "arrival",
    "check-in",
    "permission slip",
    "permission form",
    "waiver",
    "release form",
    "due",
    "deadline",
    "dress code",
    "uniform",
    "costume",
    "bring",
    "snack",
    "lunch order",
    "supplies list",
    "school supplies",
    "volunteer",
    "game",
    "match",
    "lesson",
    "tournament",
    "camp",
    "birthday party",
    "party",
    "dentist",
    "doctor",
    "pediatric",
)

PROMOTIONAL_HINTS = (
    "unsubscribe",
    "sale",
    "discount",
    "offer",
    "shop now",
    "buy now",
    "podcast",
    "episode",
    "newsletter",
    "digest",
    "sponsored",
    "listen now",
    "watch now",
    "new brand",
    "creator",
    "red carpet",
)

CHILD_ACTIVITY_HINTS = (
    "birthday",
    "party",
    "class",
    "lesson",
    "practice",
    "game",
    "recital",
    "music",
    "band",
    "voice",
    "soccer",
    "baseball",
    "basketball",
    "dance",
    "gymnastics",
    "coaching",
    "camp",
    "playdate",
    "school",
)

PERSONAL_CALENDAR_HINTS = (
    "work",
    "meeting",
    "zoom",
    "1:1",
    "lunch",
    "coffee",
    "gym",
    "yoga",
    "pilates",
    "client",
    "flight",
    "travel",
    "haircut",
    "date night",
)

ALL_DAY_HINTS = (
    "picture day",
    "field trip",
    "no school",
    "holiday",
    "break",
    "spirit day",
)

AMBIGUITY_HINTS = (
    "group a",
    "group b",
    "if ",
    "depending on",
    "tbd",
    "to be determined",
    "tentative",
    "unless",
    "waitlist",
)

SCHOOL_SENDER_HINTS = (
    "school",
    "charter",
    "academy",
    "district",
    "classroom",
    "teacher",
    "principal",
    "pta",
    "pto",
    "registrar",
    "attendance",
    ".edu",
)


def count_hint_hits(source: str, hints: tuple[str, ...]) -> int:
    return sum(1 for hint in hints if hint in source)
